"""add schedule status

Revision ID: 6e552282aa5c
Revises: f2177a728ce0
Create Date: 2026-08-23 19:25:29.375726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e552282aa5c'
down_revision: Union[str, Sequence[str], None] = 'f2177a728ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "schedule_slots",
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            server_default="pending",
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_slots', 'status')
    # ### end Alembic commands ###
