"""add processing started at

Revision ID: 7a7c021bf3b5
Revises: 6e552282aa5c
Create Date: 2026-08-23 19:57:46.725932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7c021bf3b5'
down_revision: Union[str, Sequence[str], None] = '6e552282aa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_slots', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_slots', 'processing_started_at')
    # ### end Alembic commands ###
